# Spring3 - Tasca 1

### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [22]:
import numpy as np

In [27]:
def estadist_array(lista):
    if lista.ndim !=1:
        print("Error")
    else:
        m = np.min(lista)
        mx= np.max(lista)
        mean= np.mean(lista)
        desv= np.std(lista)
        print( "El mínim és " + str(m) + ". El màxim és " + str(mx) + ". La mitja és " + str(mean) + ". La desviació és " + str(desv) + ".")

In [28]:
array = np.array([1,4,6,7,4,8,5])

        
estadist_array(array)
        
    
    

El mínim és 1. El màxim és 8. La mitja és 5.0. La desviació és 2.138089935299395.


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [29]:
def generacio_quadrat(n):
    a=np.random.randint(101,size=(n,n))
    print (a)

generacio_quadrat(3)

[[93 71 73]
 [74 11 82]
 [57 65 87]]


### Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [37]:
taula2 = np.array([[2,5,7],[4,6,8]])
taula2

array([[2, 5, 7],
       [4, 6, 8]])

In [36]:
def totals_fila(lista1):
    tf = np.sum(lista1, axis=0)
    return tf

totals_fila(taula2)

array([ 6, 11, 15])

In [35]:
def totals_columna(lista1):
    tc= np.sum(lista1, axis=1)
    return tc

totals_columna(taula2)

array([14, 18])

### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [39]:
array1 = np.array([3,6,2,8,5,7,8,9,2,1,5,6])
array2 = np.array([4,6,2,7,5,6,8,9,7,3,1,5])

In [40]:
def coef_correlacio(lista3, lista4):
    cr = np.corrcoef(lista3,lista4)
    return cr

coef_correlacio(array1,array2)

array([[1.        , 0.65826241],
       [0.65826241, 1.        ]])

El coeficient de correlació serveix principalment per determinar si hi ha una relació lineal significativa entre dues variables.

El valor del coeficient de relació pot estar entre 1 i -1. 
- Si el valor és 1 o molt proper a 1 significa que la relació lineal entre les dues variables és molt significativa. Això vol dir que si una de les variables augmenta, l'altre també ho farà.  
- Si el valor és 0 o proper a 0 vol dir que no hi ha relació lineal entre les variables de manera que el comportament d'una no afectarà al comportament de l'altre. 
- Si el valor és -1 o molt proper significa que la seva relació lineal és inversa. De manera que quan una variable augmenti l'altre disminuirà. I al revés.

Això pot servir per a predir valors d'una variable en funció de l'altre, en el cas que tinguin relació lineal significativa (tant positiva com negativa). Això permet crear models predictius precisos. I es pot aplicar a diferents camps com:

- Investigació cientifica: estudis mèdics, factors de risc, medicaments i enfermetats, ...
- Finances i economia: evaluar la relació entre diferents variables econòmiques com els preus, els tipos d'interès, l'endeutaments,...
- Ciències socials: relació entre estudis i ingresos, per evaluar la relació de la pobresa amb altres variables socials, ...